/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agungrb
 */
public class ViewPelaporan extends javax.swing.JFrame implements View {

    /**
     * Creates new form ViewPelaporan
     */
    public ViewPelaporan() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnGroup1.add(ready_kond);
        btnGroup1.add(rusak_kond);
        btnGroup1.add(onservice_kond);
        btnGroup2.add(mingguan_hist);
        btnGroup2.add(bulanan_hist);
        btnGroup2.add(tahunan_hist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup1 = new javax.swing.ButtonGroup();
        btnGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKondisi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ready_kond = new javax.swing.JRadioButton();
        rusak_kond = new javax.swing.JRadioButton();
        onservice_kond = new javax.swing.JRadioButton();
        btnOK_kond = new javax.swing.JButton();
        btnPrint_kond = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnOK_hist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelHistori = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mingguan_hist = new javax.swing.JRadioButton();
        bulanan_hist = new javax.swing.JRadioButton();
        tahunan_hist = new javax.swing.JRadioButton();
        btnPrint_hist = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pelaporan");

        tabelKondisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Lokasi Barang", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelKondisi);

        jLabel1.setText("Pilih kondisi barang");

        ready_kond.setText("ready");

        rusak_kond.setText("rusak");
        rusak_kond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rusak_kondActionPerformed(evt);
            }
        });

        onservice_kond.setText("on service");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ready_kond)
                    .addComponent(onservice_kond)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rusak_kond))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ready_kond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rusak_kond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onservice_kond)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnOK_kond.setText("OK");

        btnPrint_kond.setText("Print");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOK_kond)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint_kond)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOK_kond))
                    .addComponent(btnPrint_kond, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laporan Kondisi Barang", jPanel2);

        btnOK_hist.setText("OK");

        tabelHistori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode barang", "Tanggal", "Pengguna", "Detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelHistori);

        jLabel4.setText("Pilih Periode Laporan");

        mingguan_hist.setText("mingguan");

        bulanan_hist.setText("bulanan");

        tahunan_hist.setText("tahunan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mingguan_hist)
                    .addComponent(tahunan_hist)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulanan_hist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mingguan_hist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bulanan_hist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tahunan_hist)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnPrint_hist.setText("Print");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOK_hist)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint_hist)
                        .addContainerGap())))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOK_hist))
                    .addComponent(btnPrint_hist, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laporan Histori Barang", jPanel3);

        btnKembali.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rusak_kondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rusak_kondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rusak_kondActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnOK_hist() {
        return btnOK_hist;
    }

    public JButton getBtnOK_kond() {
        return btnOK_kond;
    }

    public JButton getBtnPrint_hist() {
        return btnPrint_hist;
    }

    public JButton getBtnPrint_kond() {
        return btnPrint_kond;
    }

    public JTable getTabelHistori() {
        return tabelHistori;
    }

    public JTable getTabelKondisi() {
        return tabelKondisi;
    }
    
    
    
    public char getKondisi() {
        if(ready_kond.isSelected()) {
            return '1';
        }
        else if(rusak_kond.isSelected()) {
            return '2';
        }
        else if(onservice_kond.isSelected()) {
            return '3';
        }
        else {
            return '0';
        }
    }
    
    public char getPeriode() {
        if(mingguan_hist.isSelected()) {
            return '1';
        }
        else if(bulanan_hist.isSelected()) {
            return '2';
        }
        else if(tahunan_hist.isSelected()) {
            return '3';
        }
        else {
            return '0';
        }
    }
    
    public void setTabelHistori(String kdbarang, String tanggal, String pengguna, String detail,int i) {
        tabelHistori.getModel().setValueAt(kdbarang, i, 0);
        tabelHistori.getModel().setValueAt(tanggal, i, 1);
        tabelHistori.getModel().setValueAt(pengguna, i, 2);
        tabelHistori.getModel().setValueAt(detail, i, 3);
    }
    
    public void setTabelKondisi(String kdbarang, String nama, String lokasi, String status,int i) {
        tabelKondisi.getModel().setValueAt(kdbarang, i, 0);
        tabelKondisi.getModel().setValueAt(nama, i, 1);
        tabelKondisi.getModel().setValueAt(lokasi, i, 2);
        tabelKondisi.getModel().setValueAt(status, i, 3);
    }
    
    public void resetTabelHistori() {
        for (int i = 0; i < 9; i++) {
            tabelHistori.getModel().setValueAt("", i, 0);
            tabelHistori.getModel().setValueAt("", i, 1);
            tabelHistori.getModel().setValueAt("", i, 2);
            tabelHistori.getModel().setValueAt("", i, 3);
        }
    }
    
    public void resetTabelKondisi() {
        for (int i = 0; i < 9; i++) {
            tabelKondisi.getModel().setValueAt("", i, 0);
            tabelKondisi.getModel().setValueAt("", i, 1);
            tabelKondisi.getModel().setValueAt("", i, 2);
            tabelKondisi.getModel().setValueAt("", i, 3);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup1;
    private javax.swing.ButtonGroup btnGroup2;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnOK_hist;
    private javax.swing.JButton btnOK_kond;
    private javax.swing.JButton btnPrint_hist;
    private javax.swing.JButton btnPrint_kond;
    private javax.swing.JRadioButton bulanan_hist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton mingguan_hist;
    private javax.swing.JRadioButton onservice_kond;
    private javax.swing.JRadioButton ready_kond;
    private javax.swing.JRadioButton rusak_kond;
    private javax.swing.JTable tabelHistori;
    private javax.swing.JTable tabelKondisi;
    private javax.swing.JRadioButton tahunan_hist;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnKembali.addActionListener(e);
        btnOK_hist.addActionListener(e);
        btnOK_kond.addActionListener(e);
        btnPrint_hist.addActionListener(e);
        btnPrint_kond.addActionListener(e);
    }
}
